title: Homebrew Formulae
description: Homebrew's package index

remote_theme: Homebrew/brew.sh

exclude:
  - bin
  - script
  - CNAME
  - LICENSE.txt
  - Rakefile
  - README.md
  - Gemfile*
  - vendor

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: :title

defaults:
  - scope:
      path: ""
    values:
      image: https://brew.sh/assets/img/homebrew-256x256.png
      search_name: Homebrew Formulae
      search_site: formulae

logo: https://brew.sh/assets/img/homebrew-256x256.png

forkme_nwo: Homebrew/formulae.brew.sh

twitter:
  username: MacHomebrew

facebook:
  publisher: https://www.facebook.com/machomebrew/
