blank_issues_enabled: false

contact_links:
- name: New issue on Homebrew/homebrew-core
  url: https://github.com/Homebrew/homebrew-core/issues/new/choose
  about: Issue with the contents of a formula page? Report it to Homebrew/homebrew-core (the macOS core tap/repository).
- name: New issue on Homebrew/homebrew-cask
  url: https://github.com/Homebrew/homebrew-cask/issues/new/choose
  about: Issue with the contents of a cask page? Report it to Homebrew/homebrew-cask (the cask tap/repository).
- name: New issue on Homebrew/linuxbrew-core
  url: https://github.com/Homebrew/linuxbrew-core/issues/new/choose
  about: Issue with the contents of a Linux formula page?  Report it to Homebrew/linuxbrew-core (the Linux core tap/repository).
